### ISSUE TITLE
关于JD_spider.py中保存出的xlsx文件名字乱码的问题

### ISSUE THREAD

**Issue by Alucardlucas** [Fenghuapiao/PythonCrawler#2]
33行处data.to_excel('./家居用品s.xlsx', index=False)  保存在目录下的表格名字是乱码请问要怎么解决

**Comment by Fenghuapiao** [comment]
这个我本机测试没有问题呢！

**Comment by Fenghuapiao** [comment]
你可能没安装好读写excel的moudle,你可以改成保存为.csv文件！

**Comment by Alucardlucas** [comment]
您用的是linux还是win7?我在win7的shell中执行出来中文好像一直是乱码， JD_spider.py我也就在首行写了#coding:utf-8

**Comment by Fenghuapiao** [comment]
py3不需要开头加那句话，win7是可以的！你先改成to_csv试下。

**Comment by Alucardlucas** [comment]
好的我明天再尝试一下，谢谢您，早点休息

**Comment by Fenghuapiao** [comment]
有问题再讨论呢。
