### ISSUE TITLE
how to change the code to crawl data from following website

### ISSUE THREAD

**Issue by jren2017** [Fenghuapiao/PythonCrawler#4]
![image](https://user-images.githubusercontent.com/24396551/31320016-0709e3a6-acca-11e7-83a7-527c46907c4e.png)

http://fund.jrj.com.cn/archives,001644,jjjz.shtml

Hello, 
I want to crawl the data from this website, could you help explain how to do it? 

is there any example available?

**Comment by Fenghuapiao** [comment]
First of all, you have to understand the basic principles of WebSpider.

**Comment by Fenghuapiao** [comment]
make the best of Google.
